import { defineField, defineType } from 'sanity'

export default defineType({
  name: 'resource',
  title: 'Resource',
  type: 'document',
  fields: [
    defineField({
      name: 'title',
      title: 'Title',
      type: 'string',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'slug',
      title: 'Slug',
      type: 'slug',
      options: {
        source: 'title',
        maxLength: 96,
      },
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'description',
      title: 'Description',
      type: 'text',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'content',
      title: 'Content',
      type: 'array',
      of: [{ type: 'block' }],
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'domain',
      title: 'Domain',
      type: 'reference',
      to: [{ type: 'domain' }],
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'relatedNodes',
      title: 'Related Nodes',
      type: 'array',
      of: [{
        type: 'reference',
        to: [{ type: 'node' }],
        weak: true
      }],
    }),
    defineField({
      name: 'tags',
      title: 'Tags',
      type: 'array',
      of: [{ type: 'string' }],
    }),
    defineField({
      name: 'source',
      title: 'Source',
      type: 'string',
      description: 'Research source or origin of this resource',
    }),
    defineField({
      name: 'externalLinks',
      title: 'External Links',
      type: 'array',
      of: [
        {
          type: 'object',
          fields: [
            {
              name: 'title',
              title: 'Title',
              type: 'string',
              validation: (Rule) => Rule.required(),
            },
            {
              name: 'url',
              title: 'URL',
              type: 'url',
              validation: (Rule) => Rule.required(),
            },
            {
              name: 'description',
              title: 'Description',
              type: 'text',
            },
          ],
        },
      ],
    }),
    defineField({
      name: 'isAIGenerated',
      title: 'Is AI Generated',
      type: 'boolean',
      description: 'Whether this resource was generated by AI',
    }),
    defineField({
      name: 'generationPrompt',
      title: 'Generation Prompt',
      type: 'text',
      description: 'The prompt used to generate this resource (if AI-generated)',
    }),
  ],
  preview: {
    select: {
      title: 'title',
      domain: 'domain.title',
    },
    prepare(selection) {
      const { title, domain } = selection
      return {
        title,
        subtitle: domain ? `Domain: ${domain}` : '',
      }
    },
  },
}) 